name: nathanryan
favicon: null
layout_spectrum: 0.75454
typography_spectrum: 0.23339
title: This is Everything
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242f45'
    - '#ffffff'
    - '#030200'
    - '#5b5f6a'
    - '#a1978d'
  brandStrength: 0.0625
  lightness: 0.8847700587939471
  saturation: 0.49099101638421416
  rhythmicContrast: 0.9617950459942222
purpose: []
